import json
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal, NotRequired, TypedDict

from langchain.agents import AgentState
from langchain.agents.middleware import InputAgentState, OutputAgentState
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import BaseMessage, HumanMessage
from langgraph.graph import END, START, StateGraph
from langgraph.graph.state import CompiledStateGraph
from langgraph.runtime import Runtime

from switchboard.change_management import save_proposal
from switchboard.dynamodb import DynamoStore
from switchboard.integrations.policy_library import list_policies
from switchboard.investigation.evidence import capture_investigation_evidence
from switchboard.investigation.report_validation import (
    PolicySource,
    validate_investigation_report,
)
from switchboard.investigation.tools import InvestigationContext, employee_session
from switchboard.models import (
    EndpointChangeResult,
    EvidenceSnapshot,
    InvestigationDraft,
    InvestigationResult,
    Proposal,
    ReportValidation,
)
from switchboard.proposals import validate_proposal


# Dependencies supplied by the application that the workflow will use
@dataclass(frozen=True)
class EndpointChangeContext:
    agent: CompiledStateGraph[
        AgentState[Any],
        InvestigationContext | None,
        InputAgentState,
        OutputAgentState[Any],
    ]
    model: BaseChatModel
    investigation_context: InvestigationContext
    captured_at: datetime


class EndpointChangeWorkflowState(TypedDict):
    request: str
    ticket_id: str
    source: NotRequired[Literal["model"]]
    investigation: NotRequired[InvestigationResult]
    report_validation: NotRequired[ReportValidation]
    evidence: NotRequired[list[EvidenceSnapshot]]
    proposal: NotRequired[Proposal]
    was_created: NotRequired[bool]
    messages: NotRequired[list[BaseMessage]]


def investigate_request(
    state: EndpointChangeWorkflowState, runtime: Runtime[EndpointChangeContext]
):
    # 1. Resume only the private draft belonging to this workspace generation and job.
    storage = runtime.context.investigation_context.storage
    cached = (
        storage.transport.load_checkpoint(storage.workspace_id, stage="draft")
        if isinstance(storage.transport, DynamoStore)
        else None
    )

    # 2. Resume the draft or run the investigator's authorized read-only tools.
    if cached is not None:
        draft = InvestigationDraft.model_validate_json(json.dumps(cached))
    else:
        result = runtime.context.agent.invoke(
            {"messages": [HumanMessage(content=state["request"])]},
            context=runtime.context.investigation_context,
            config={"recursion_limit": 12},
        )
        if "structured_response" in result:
            investigation = InvestigationResult.model_validate(
                result["structured_response"]
            )
        else:
            investigation = InvestigationResult.model_validate_json(
                result["messages"][-1].text
            )
        draft = InvestigationDraft(
            ticket_id=state["ticket_id"],
            investigation=investigation,
            evidence=capture_investigation_evidence(
                messages=result["messages"],
                captured_at=runtime.context.captured_at,
            ),
            messages=result["messages"],
        )

    # 3. Keep the selected ticket authoritative and fence every checkpoint write.
    if draft.ticket_id != state["ticket_id"] or (
        draft.investigation.ticket_id is not None
        and draft.investigation.ticket_id != state["ticket_id"]
    ):
        raise ValueError("Investigation returned a different ticket")
    if cached is None and isinstance(storage.transport, DynamoStore):
        storage.transport.save_checkpoint(
            storage.workspace_id, draft.model_dump(mode="json"), stage="draft"
        )

    # 4. Both fresh and resumed drafts must pass the following policy-review node.
    return {
        "source": "model",
        "investigation": draft.investigation,
        "evidence": draft.evidence,
        "messages": draft.messages,
    }


def validate_report(
    state: EndpointChangeWorkflowState, runtime: Runtime[EndpointChangeContext]
):
    """Validate the report against current workspace policies before routing it."""
    # 1. Require the draft generated by the investigator.
    investigation = state.get("investigation")
    if investigation is None:
        raise ValueError("Cannot validate a missing investigation")

    # 2. Load the same workspace policies available to the active employee.
    with employee_session(runtime.context.investigation_context) as session:
        policies = [
            PolicySource.model_validate(policy) for policy in list_policies(session)
        ]

    # 3. Validate policy wording and return the accepted report and receipt.
    validated = validate_investigation_report(
        draft=investigation,
        policies=policies,
        model=runtime.context.model,
    )
    evidence = list(state.get("evidence", []))
    captured_ids = {item.id for item in evidence}
    evidence.extend(
        EvidenceSnapshot(
            id=policy.id,
            kind="policy",
            captured_at=runtime.context.captured_at,
            document=policy,
        )
        for policy in policies
        if policy.id not in captured_ids
    )
    storage = runtime.context.investigation_context.storage
    if isinstance(storage.transport, DynamoStore):
        accepted = EndpointChangeResult.model_validate(
            {
                "source": "model",
                "investigation": validated.investigation,
                "report_validation": validated.validation,
                "evidence": evidence,
                "messages": state.get("messages", []),
            }
        )
        storage.transport.save_checkpoint(
            storage.workspace_id, accepted.model_dump(mode="json")
        )
    return {
        "investigation": validated.investigation,
        "report_validation": validated.validation,
        "evidence": evidence,
    }


def prepare_proposal(
    state: EndpointChangeWorkflowState, runtime: Runtime[EndpointChangeContext]
):
    # 1. Require a completed investigation.
    investigation = state.get("investigation")
    if investigation is None:
        raise ValueError("Cannot prepare a proposal without an investigation")

    # 2. Validate and save using the trusted employee session.
    with employee_session(runtime.context.investigation_context) as session:
        proposal = validate_proposal(investigation=investigation, session=session)
        saved_proposal = save_proposal(proposal=proposal, session=session)
        proposal = saved_proposal.proposal
        was_created = saved_proposal.was_created

    # 3. Return the saved proposal and whether it was created.
    return {"proposal": proposal, "was_created": was_created}


def route_after_investigation(state: EndpointChangeWorkflowState):
    # 1. Require the result produced by the investigation node.
    investigation = state.get("investigation")

    if investigation is None:
        raise ValueError("Cannot route without an investigation result")

    # 2. Return the outcome used by the conditional edge.
    return investigation.outcome


# Create the graph
workflow = StateGraph(
    EndpointChangeWorkflowState,
    context_schema=EndpointChangeContext,
    output_schema=EndpointChangeResult,
)

# Add nodes
workflow.add_node("investigate_request", investigate_request)
workflow.add_node("validate_report", validate_report)
workflow.add_node("prepare_proposal", prepare_proposal)

# Add edges
workflow.add_edge(START, "investigate_request")
workflow.add_edge("investigate_request", "validate_report")
workflow.add_conditional_edges(
    "validate_report",
    route_after_investigation,
    path_map={
        "proposal_candidate": "prepare_proposal",
        "blocked": END,
    },
)
workflow.add_edge("prepare_proposal", END)
endpoint_change_graph = workflow.compile()
